#!/usr/bin/env python3
"""
Standalone Pre-Mortem Analysis Tool

Forces failure-first thinking on any proposal by generating a structured
pre-mortem analysis template.

Usage:
    python3 pre_mortem.py "Proposal Title"
    python3 pre_mortem.py --interactive
    python3 pre_mortem.py --scenarios
"""

from __future__ import annotations

import sys
from datetime import datetime

PRE_MORTEM_TEMPLATE = """# Pre-Mortem Analysis: {title}

**Date**: {date}
**Analyst**: The Judge (Adversarial Validator)

---

## Frame Shift

> It is six months from now. This implementation has failed catastrophically.
> You are conducting the post-failure analysis. What happened?

---

## Failure Modes Identified

### Failure Mode 1: [Title]

| Aspect | Analysis |
|--------|----------|
| **Trigger** | What specific condition caused this to fail? |
| **Root Cause** | What design decision enabled this failure? |
| **Warning Signs** | What should have been caught during review? |
| **Blast Radius** | What else broke when this failed? |
| **Mitigation** | What specific change would have prevented this? |

### Failure Mode 2: [Title]

| Aspect | Analysis |
|--------|----------|
| **Trigger** | |
| **Root Cause** | |
| **Warning Signs** | |
| **Blast Radius** | |
| **Mitigation** | |

### Failure Mode 3: [Title]

| Aspect | Analysis |
|--------|----------|
| **Trigger** | |
| **Root Cause** | |
| **Warning Signs** | |
| **Blast Radius** | |
| **Mitigation** | |

---

## Temporal Scenarios

Answer each scenario as if it has already happened:

### The 3 AM Page
> The on-call engineer was woken up by PagerDuty. What happened?

**Incident Report**:


### The Security Disclosure
> A security researcher submitted a responsible disclosure. What vulnerability did they find?

**CVE Description**:


### The Customer Escalation
> A major customer is threatening to leave due to data issues. What went wrong?

**Customer Impact**:


### The New Hire Question
> A new team member asked "why is this so complicated?" What's the honest answer?

**Technical Debt Explanation**:


### The Post-Incident Review
> The team gathered for a blameless post-mortem. What were the key findings?

**Findings**:
1.
2.
3.

---

## Risk Matrix

| Failure Mode | Likelihood | Impact | Priority | Mitigation Status |
|--------------|------------|--------|----------|-------------------|
| Mode 1 | HIGH / MED / LOW | HIGH / MED / LOW | P0 / P1 / P2 | NOT STARTED |
| Mode 2 | HIGH / MED / LOW | HIGH / MED / LOW | P0 / P1 / P2 | NOT STARTED |
| Mode 3 | HIGH / MED / LOW | HIGH / MED / LOW | P0 / P1 / P2 | NOT STARTED |

**Priority Definitions**:
- **P0**: Must address before proceeding. Blocking.
- **P1**: Should address before production. High severity.
- **P2**: Address within sprint. Medium severity.

---

## Required Mitigations Before Approval

Based on this pre-mortem analysis, the following must be addressed:

1. [ ] **[Mitigation for highest-priority failure mode]**
2. [ ] **[Mitigation 2]**
3. [ ] **[Mitigation 3]**

---

## Questions for the Proposal Author

1. How does the current design handle [identified failure trigger]?
2. What monitoring/alerting exists for [failure mode]?
3. What is the recovery procedure for [scenario]?
4. Has [assumption] been validated?

---

## Verdict Recommendation

Based on this pre-mortem analysis:

- [ ] **APPROVED** - No significant failure modes identified
- [ ] **APPROVED WITH CONDITIONS** - Proceed after addressing P1 items
- [ ] **REVISE AND RESUBMIT** - Multiple high-severity issues need redesign
- [ ] **BLOCKED** - P0 issues must be resolved before proceeding

**Justification**:


---

*Generated by Pre-Mortem Analysis Tool - Adversarial Validator*
"""

TEMPORAL_SCENARIOS = [
    {
        "name": "The 3 AM Page",
        "prompt": "The on-call engineer was woken up by PagerDuty at 3 AM. What caused the alert?",
        "focus": "Operational failures, monitoring gaps, unclear runbooks",
    },
    {
        "name": "The Security Disclosure",
        "prompt": "A security researcher just published a CVE for your system. What did they find?",
        "focus": "Authentication, authorization, injection, data exposure",
    },
    {
        "name": "The Customer Escalation",
        "prompt": "A major customer is demanding a refund due to data issues. What happened?",
        "focus": "Data integrity, availability, correctness",
    },
    {
        "name": "The New Hire Question",
        "prompt": "A new hire asked 'why is this so complicated?' What's the answer?",
        "focus": "Technical debt, unnecessary complexity, documentation gaps",
    },
    {
        "name": "The Post-Incident Review",
        "prompt": "The team gathered for a blameless post-mortem. What were the findings?",
        "focus": "Root causes, systemic issues, process failures",
    },
    {
        "name": "The Audit Finding",
        "prompt": "An external audit found compliance violations. What was missed?",
        "focus": "Logging, access control, data retention, privacy",
    },
    {
        "name": "The Scale Crisis",
        "prompt": "The system fell over during peak traffic (10x normal). What wasn't scaled?",
        "focus": "Bottlenecks, resource limits, single points of failure",
    },
    {
        "name": "The Migration Disaster",
        "prompt": "The data migration corrupted production data. What went wrong?",
        "focus": "Data validation, rollback procedures, testing",
    },
]


def generate_template(title: str) -> str:
    """Generate a pre-mortem analysis template."""
    return PRE_MORTEM_TEMPLATE.format(
        title=title,
        date=datetime.now().strftime("%Y-%m-%d"),
    )


def print_scenarios():
    """Print all temporal scenarios with guidance."""
    print("\n=== Pre-Mortem Temporal Scenarios ===\n")
    print("Use these scenarios to force failure-first thinking:\n")

    for i, scenario in enumerate(TEMPORAL_SCENARIOS, 1):
        print(f"### {i}. {scenario['name']}")
        print(f"    Prompt: \"{scenario['prompt']}\"")
        print(f"    Focus: {scenario['focus']}")
        print()

    print("\nUsage: For each scenario, write as if the failure has already occurred.")
    print("This shift from 'might happen' to 'did happen' surfaces hidden risks.\n")


def interactive_mode():
    """Run interactive pre-mortem session."""
    print("\n=== Interactive Pre-Mortem Session ===\n")
    print("I'll guide you through failure-mode analysis.\n")

    title = input("What is the name of the proposal/design? > ").strip()
    if not title:
        title = "Untitled Proposal"

    print(f"\n--- Analyzing: {title} ---\n")
    print("Frame shift: Assume this has already failed catastrophically.\n")

    findings = []

    for scenario in TEMPORAL_SCENARIOS[:4]:  # Use first 4 scenarios
        print(f"\n### {scenario['name']}")
        print(f"Prompt: {scenario['prompt']}")
        print(f"(Focus on: {scenario['focus']})")
        print()
        response = input("What happened? > ").strip()
        if response:
            findings.append(f"{scenario['name']}: {response}")

    print("\n\n=== Pre-Mortem Findings ===\n")
    for finding in findings:
        print(f"- {finding}")

    print("\n\nTo generate a full template, run:")
    print(f'    python3 pre_mortem.py "{title}"')


def print_usage():
    """Print usage information."""
    print("""
Pre-Mortem Analysis Tool - Adversarial Validator

Forces failure-first thinking by assuming the proposal has already failed.

Usage:
    python3 pre_mortem.py "Proposal Title"    Generate analysis template
    python3 pre_mortem.py --interactive       Guided analysis session
    python3 pre_mortem.py --scenarios         List temporal scenarios
    python3 pre_mortem.py --help              Show this help

The pre-mortem technique shifts thinking from "what could go wrong" to
"what DID go wrong" - surfacing risks that optimism blindness hides.

Example:
    python3 pre_mortem.py "Authentication Refactor" > auth_premortem.md
""")


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print_usage()
        sys.exit(1)

    arg = sys.argv[1]

    if arg in ("--help", "-h"):
        print_usage()
        sys.exit(0)
    elif arg == "--scenarios":
        print_scenarios()
        sys.exit(0)
    elif arg == "--interactive":
        interactive_mode()
        sys.exit(0)
    else:
        # Treat argument as proposal title
        title = " ".join(sys.argv[1:])
        print(generate_template(title))


if __name__ == "__main__":
    main()
